name: Test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install stable toolchain
              run: rustup toolchain install stable

            - name: Install dependencies
              run: sudo apt-get install libpango1.0-dev

            - name: Cache dependencies
              uses: Swatinem/rust-cache@v2

            - name: Build
              run: cargo build
              continue-on-error: false

            - name: Formatting
              uses: actions-rs/cargo@v1
              with:
                command: fmt
              continue-on-error: false

            - name: Lint
              run: cargo clippy
              continue-on-error: false
